apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: express-secret
data:
  ME_CONFIG_MONGODB_ADMINUSERNAME: YWRtaW4=
  ME_CONFIG_MONGODB_ADMINPASSWORD: cGFzc3dvcmQ=
