apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    team: team-a
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    team: team-a
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    team: team-a
spec:
  containers:
  - name: nginx
    image: nginx