apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  username: dnN1c2hrbwo=
  password: YWRtaW4xMjMK
---
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    envFrom:
    - secretRef:
        name: app-secret
    args:
    - env