apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    dept: dept-1
    team: team-a
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    dept: dept-2
    team: team-b
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    dept: dept-2
    team: team-c
spec:
  containers:
  - name: nginx
    image: nginx